### PR TITLE
Feature/async support

### PR DESCRIPTION
**Pull request by jhonrope**
Hi Joe, I followed your recommendation about how the plugin should support our case scenario when working with requireJs.

I created the test-project requireJs and made some changes to busy wait the signal or some timeout to execute the tests.

I also changed the README. I'm sorry about grammar or something, English is not my native language!

Jhony

### CODE REVIEW

**Comment by joescii** [comment]
Thanks for the contribution! I assume it is working well for you. I will take a look when I get a chance and get it merged in. I'm pretty busy right now with a new job and a move, so don't be shy to ping me if I am slow to move.

**Comment by joescii** [comment]
@jhonrope Take a look at [my async branch](https://github.com/joescii/sbt-js-test/tree/async). I've made a few changes:
1. Renamed the keys to `jsAsyncWait` and `jsAsyncWaitTimeout`.
2. Changed `jsAsyncWaitTimeout` to be `Option[Long]`, defaulting to `None`.
3. Created a second requireJs test to verify that the timeout feature works.

I felt like the timeout really should be optional. This way if you turn on `jsAsyncWait` it'll just hang indefinitely, which I think will be less confusing than running earlier than expected like you experienced. The best way to do this is with the callback like you were able to do with requireJs.

Take a look and let me know if you think these are good changes, and I'll get this shipped.

**Comment by jhonrope** [comment]
HI Joe, I agree all your changes. Definitely timeout should be optional for the reasons you describe.

We are waiting for you to ship the new version as soon as possible!

Thank you!

**Comment by joescii** [comment]
@jhonrope try `0.2.0`!

**Comment by jhonrope** [comment]
Thank you very much. This works like a charm! 

I hope this can help others with the same needs.

**Pull request merged**
